base_config:
 github_token: 
 #发件人邮箱
 my_sender: 
 #发件人授权码/密码
 my_pass: 
 #收件人邮箱
 recipients: 
 #发件人smtp服务器地址
 smtp_server: smtp.qq.com
 #smtp端口号
 smtp_port: 465
 #资产xlsx表地址
 xlsx_filename: 
 #读取的表格号
 sheet_number: Sheet1
 #server酱
 server: 

database_config:
  database_name: 123
  database_pass: 123


